/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 012e1e8c0f466b4f9bab89952ba51005)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NODE_ENV: "production";
	NEXT_INC_CACHE_R2_PREFIX: "rowdyhacks-xii-web";
	WORKER_SELF_REFERENCE: Fetcher /* rowdyhacks-xii-web */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "NEXT_INC_CACHE_R2_PREFIX" >> {} }
}
