export const ONE_HOUR_IN_MILLISECONDS = 3600000;
export const FIVE_MINUTES_IN_MILLISECONDS = 300000;
export const VERCEL_IP_TIMEZONE_HEADER_KEY = "x-vercel-ip-timezone";
export const UNIQUE_KEY_CONSTRAINT_VIOLATION_CODE = "23505";
export const PAYLOAD_TOO_LARGE_CODE = 413;
