import type { HackKitUIActions } from "@hackkit/ui";
import {
	approveUser,
	assignRoleToUser,
	banUser,
	cancelRsvp,
	checkInUser,
	claimHackTag,
	clearCheckIn,
	completeUserData,
	confirmRsvp,
	createEvent,
	createRole,
	deleteEvent,
	deleteRole,
	listSettings,
	previewEventPassQr,
	promoteRsvp,
	recordEventScan,
	registerHacker,
	resetSetting,
	setRsvpStatus,
	setSettings,
	unbanUser,
	updateEvent,
	updateRole,
	updateUserProfile,
} from "./server-actions";

/**
 * Serializable action references supplied to the client-side UI provider.
 * Keep this separate from the "use server" module because that module may only
 * export async Server Action functions.
 */
export const hackKitUIActions = {
	completeUserData,
	claimHackTag,
	updateUserProfile,
	registerHacker,
	createEvent,
	updateEvent,
	deleteEvent,
	previewEventPassQr,
	recordEventScan,
	checkInUser,
	clearCheckIn,
	confirmRsvp,
	cancelRsvp,
	setRsvpStatus,
	promoteRsvp,
	approveUser,
	banUser,
	unbanUser,
	assignRoleToUser,
	createRole,
	updateRole,
	deleteRole,
	listSettings,
	setSettings,
	resetSetting,
} satisfies HackKitUIActions;
